### ISSUE TITLE
Suggestion: add a check for all unique non-overlapping values of FCS "cellSubset" and marker "fixed"

### ISSUE THREAD

**Issue by mjdufort** [BenaroyaResearch/briDiscovr#1]
In the dataset I'm working with, one cellSubset was named "CD4" by the investigators.  There is also a marker with the name / "fixed" value of "CD4".  This led to an error in when running `metaclusterDiscovrExperiment`, as the cellSubset and marker names are column names in two data frames that get joined.  The join is in metaclusteringPhase.R, lines 66-77.  If there are duplicated names between cellSubset and commonMarkerName, those duplicates are renamed [name].x and [name].y.  This causes an in the code on lines 143-151, as the column name matching the subset cannot be found.

It may seem like an obviously bad idea to have a cell subset and a marker with the same name, but I can see this happening routinely.  I suggest adding an additional check in `setupDiscovrExperiment` to require non-overlapping names for markers and cell subsets.

**Comment by DrxMario** [comment]
Thanks very much for identifying this, Matt. Should be resolved with commit 8700e86a3cb4f0440cd7c29d79a8d14ee62d92b1 - please let me know if you still encounter any issues.
