### ISSUE TITLE
Marker names with special characters create conflicts

### ISSUE THREAD

**Issue by mjdufort** [BenaroyaResearch/briDiscovr#2]
If the marker names include any names that are not syntactically valid, they are coerced to syntactically valid names within `setupDiscovrExperiment`, within the internal function `processData `, line 217 of clusteringPhase.R.  However, the markers retain their original invalid names within the markerInfo component of the discovrExperiment object.  This causes conflicts downstream, notably in the `select` statement on line 180 of metaclusteringPhase.R.  Because the column names do not match between `markerInfo$commonMarkerName` and the column names of various data frames, those columns with originally invalid names are excluded from a number of components of the discovrExperiment object.  It's possible they are excluded from additional components, I have verified they are missing from allSubsetAllSubjectZscores, allSubsetAllSubjectArcsinh.

I do not know the reason for coercing the marker names to syntactically valid names, but I suspect removing that step and having invalid column names may break things downstream.  I suggest coercing the marker names in markerInfo within setupDiscovrExperiment, to match the column names elsewhere, with a warning to the user listing the syntactically invalid names pre- and post-coercion.

**Comment by mjdufort** [comment]
One thing to add - I tested this by modifying the names in my marker information file using `make.names`.  I verified that all steps worked, through make `makeMetaclusterHeatmaps`.  So I do not think that changing the marker names introduces any additional conflicts e.g. with the .fcs files and/or flowFrame objects.

**Comment by DrxMario** [comment]
Thanks for reporting this, Matt. This should be resolved as of 0e865dc10ea85889b3ad7d23d93941876a5dae90.

Thanks!
