### ISSUE TITLE
Bug in clusterDiscovrExperiment

### ISSUE THREAD

**Issue by mjdufort** [BenaroyaResearch/briDiscovr#6]
In the most recent commit, line 426 of clusteringPhase.R changed from `experiment$mergedExpr <- subset(experiment$mergedExpr, select = -rowIdx)` to `experiment$mergedExpr <- subset(experiment$mergedExpr, select = -.data$rowIdx)`.  As there is no object piped to `subset`, the `.data` is not found, resulting in an error.

**Comment by DrxMario** [comment]
Fixed as of ec8c3f794ffeb40a226f58a6a5a4b9f59304de19. Thanks!
